name: Build and Deploy to GitHub Pages

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install mold
        uses: rui314/setup-mold@v1

      - name: Setup wasm-bindgen
        uses: taiki-e/install-action@v2
        with:
          tool: wasm-bindgen@0.2.113

      - name: Setup Trunk
        uses: taiki-e/install-action@v2
        with:
          tool: trunk

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: Build wasm bundle
        run: |
          cargo build --target wasm32-unknown-unknown --release -p client
          wasm-bindgen --out-dir ./web/dist --target web target/wasm32-unknown-unknown/release/client.wasm

      - name: Build web assets with Trunk
        run: trunk build --release --config web/Trunk.toml

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/dist
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
